version: '3.6'
services:
  config_server:
    container_name: config_server
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      DB_HOST: ${DB_HOST-localhost}
      DB_LOGIN: ${DB_USER-root}
      DB_PASS: ${DB_PASS-1234}
      DB_NAME: config_server
      CONTAINER_PORT: ${CONFIG_SERVER_CONTAINER_PORT-80}
      OUTER_PORT: ${OUTER_PORT-80}
      SUBPATH: ${SUBPATH-/config_server}
      OUTER_SCHEME : ${OUTER_SCHEME}
      OUTER_HOST : ${OUTER_HOST}
      M_TOKEN: ${M_TOKEN}
      AUTH_SECRET: ${AUTH_SECRET}
#    ports:
#      - 82:81
networks:
  dc-net:
    external: true