version: '3.6'
services:
  config_server:
    container_name: config_server
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      DB_HOST: ${DB_HOST-localhost}
      DB_LOGIN: ${DB_USER-root}
      DB_PASS: ${DB_PASS-1234}
      DB_NAME: config_server
      CONTAINER_PORT: ${CONFIG_SERVER_CONTAINER_PORT-80}
      OUTER_PORT: ${OUTER_PORT-80}
      LOGOTIPIWE_GMAIL_ID: ${LOGOTIPIWE_GMAIL_ID}
      G_OAUTH_CLIENT_SECRET: ${G_OAUTH_CLIENT_SECRET}
      SUBPATH: ${SUBPATH-/config_server}
      OUTER_SCHEME : ${OUTER_SCHEME}
      OUTER_HOST : ${OUTER_HOST}
      IDP_HOST: ${IDP_HOST-http://idp}
      IDP_SUBPATH: ${IDP_SUBPATH-}
      M_TOKEN: ${M_TOKEN}
#    ports:
#      - 82:81
networks:
  dc-net:
    external: true