version: '3.6'
services:
  config_server:
    container_name: config_server
    restart: always
    image: logotipiwe/config_server
    build: .
    networks:
      - dc-net
    environment:
      DB_HOST: ${DB_HOST}
      DB_LOGIN: ${DB_USER}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: config_server
      PORT: ${CONFIG_SERVER_CONTAINER_PORT-80}
      LOGOTIPIWE_GMAIL_ID: ${LOGOTIPIWE_GMAIL_ID}
#    ports:
#      - 82:81
networks:
  dc-net:
    external: true